# Generated by Django 2.2.4 on 2019-08-23 20:43

from django.db import migrations, models
import django.db.models.deletion
import urlshortener.models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0002_remove_shorturl_times_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shorturl',
            options={'verbose_name': 'Short url', 'verbose_name_plural': 'Short urls'},
        ),
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name': 'Useragent', 'verbose_name_plural': 'Useragents'},
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='basic_url',
            field=urlshortener.models.ExtendedUrlField(verbose_name='Main url'),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Clicks count'),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='description',
            field=models.CharField(max_length=80, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='last_click',
            field=models.DateTimeField(null=True, verbose_name='Last click'),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='short_id',
            field=models.SlugField(max_length=10, null=True, verbose_name='Short ID'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='click_time',
            field=models.DateTimeField(null=True, verbose_name='Click'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='short_url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='urlshortener.ShortUrl', verbose_name='Short url'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_data',
            field=models.TextField(default='[]', null=True, verbose_name='User agent'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_ip',
            field=models.CharField(default='', max_length=15, null=True, verbose_name='IP'),
        ),
    ]
