# Generated by Django 2.2.4 on 2019-10-02 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(max_length=20, verbose_name='Typeform ID')),
                ('name', models.CharField(max_length=500, verbose_name='Form name')),
                ('form_type', models.CharField(blank=True, choices=[('initial', 'INITIAL'), ('other', 'OTHER')], max_length=40, null=True, verbose_name='Form type')),
            ],
            options={
                'verbose_name': 'Typeform',
                'verbose_name_plural': 'Typeforms',
            },
        ),
        migrations.CreateModel(
            name='TypeFormQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=20, verbose_name='Question ID')),
                ('field_name', models.CharField(max_length=500, verbose_name='Field name')),
                ('form', models.ForeignKey(on_delete=None, related_name='questions', to='typeform.TypeForm', verbose_name='TypeForm')),
            ],
            options={
                'verbose_name': 'TypeForm question',
                'verbose_name_plural': 'TypeForm questions',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('submitted_at', models.DateTimeField(verbose_name='Submitted at')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('content', models.TextField(verbose_name='Content')),
                ('hidden_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hidden ID')),
                ('hidden_data', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hidden fields')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Score')),
                ('answers', models.TextField(blank=True, null=True, verbose_name='Answers')),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='typeform.TypeForm', verbose_name='Form ID')),
            ],
            options={
                'verbose_name': 'TypeForm result',
                'verbose_name_plural': 'TypeForm results',
            },
        ),
    ]
