# Generated by Django 2.2.4 on 2019-08-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typeform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeform',
            name='form_type',
            field=models.CharField(blank=True, choices=[('INITIAL', 'initial'), ('OTHER', 'other')], max_length=40, null=True, verbose_name='Тип формы'),
        ),
    ]
