# Generated by Django 2.2.4 on 2019-08-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typeform', '0002_typeform_form_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeform',
            name='form_type',
            field=models.CharField(blank=True, choices=[('initial', 'INITIAL'), ('other', 'OTHER')], max_length=40, null=True, verbose_name='Тип формы'),
        ),
    ]
