# Generated by Django 2.2.4 on 2019-08-23 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typeform', '0003_auto_20190823_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name': 'TypeForm result', 'verbose_name_plural': 'TypeForm results'},
        ),
        migrations.AlterModelOptions(
            name='typeform',
            options={'verbose_name': 'Typeform', 'verbose_name_plural': 'Typeforms'},
        ),
        migrations.AlterModelOptions(
            name='typeformquestion',
            options={'verbose_name': 'TypeForm question', 'verbose_name_plural': 'TypeForm questions'},
        ),
        migrations.AlterField(
            model_name='result',
            name='answers',
            field=models.TextField(blank=True, null=True, verbose_name='Answers'),
        ),
        migrations.AlterField(
            model_name='result',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='result',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='result',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='typeform.TypeForm', verbose_name='Form ID'),
        ),
        migrations.AlterField(
            model_name='result',
            name='hidden_data',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hidden fields'),
        ),
        migrations.AlterField(
            model_name='result',
            name='hidden_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hidden ID'),
        ),
        migrations.AlterField(
            model_name='result',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='result',
            name='submitted_at',
            field=models.DateTimeField(verbose_name='Submitted at'),
        ),
        migrations.AlterField(
            model_name='typeform',
            name='form_id',
            field=models.CharField(max_length=20, verbose_name='Typeform ID'),
        ),
        migrations.AlterField(
            model_name='typeform',
            name='form_type',
            field=models.CharField(blank=True, choices=[('initial', 'INITIAL'), ('other', 'OTHER')], max_length=40, null=True, verbose_name='Form type'),
        ),
        migrations.AlterField(
            model_name='typeform',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Form name'),
        ),
        migrations.AlterField(
            model_name='typeformquestion',
            name='field_name',
            field=models.CharField(max_length=500, verbose_name='Field name'),
        ),
        migrations.AlterField(
            model_name='typeformquestion',
            name='question_id',
            field=models.CharField(max_length=20, verbose_name='Question ID'),
        ),
    ]
