# Generated by Django 2.2.4 on 2019-10-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InviteEmailText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Email title')),
                ('body', models.TextField(help_text='Your email address %s and your password %s', verbose_name='Email body')),
            ],
            options={
                'verbose_name': 'Invitation email',
                'verbose_name_plural': 'Invitation emails',
            },
        ),
        migrations.CreateModel(
            name='RepeatedEmailText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Email title')),
                ('body', models.TextField(help_text='Url for request = %', verbose_name='Email body')),
            ],
            options={
                'verbose_name': 'Email on repeat',
                'verbose_name_plural': 'Emails on repeat',
            },
        ),
    ]
