# Generated by Django 2.2.4 on 2019-08-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InviteEmailText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_title', models.TextField(verbose_name='Текст заголовка письма')),
                ('email_body', models.TextField(verbose_name='Текст письма')),
            ],
        ),
    ]
