# Generated by Django 2.2.4 on 2019-08-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inviteemailtext',
            options={'verbose_name': 'Invitation email', 'verbose_name_plural': 'Invitation emails'},
        ),
        migrations.RemoveField(
            model_name='inviteemailtext',
            name='email_body',
        ),
        migrations.RemoveField(
            model_name='inviteemailtext',
            name='email_title',
        ),
        migrations.AddField(
            model_name='inviteemailtext',
            name='body',
            field=models.TextField(default=' ', verbose_name='Email body'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inviteemailtext',
            name='title',
            field=models.TextField(default=' ', verbose_name='Email title'),
            preserve_default=False,
        ),
    ]
