# Generated by Django 2.2.4 on 2019-08-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190823_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteemailtext',
            name='body',
            field=models.TextField(help_text='Your email address %s and your password %s', verbose_name='Email body'),
        ),
    ]
